spring:
  application:
    name: fish-corp-backend

api:
  metno:
    base-url: https://api.met.no
  kartverket:
    base-url: https://kartverket.no

logging:
  level:
    org:
      springframework:
        web: DEBUG